"""add injury class and medical records

Revision ID: 3218ec759fe6
Revises: e22b636bd402
Create Date: 2024-12-02 10:09:28.275801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3218ec759fe6'
down_revision = 'e22b636bd402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('injury_classes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('class_name', sa.String(length=50), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name')
    )
    op.create_table('medical_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('photo_date', sa.DateTime(), nullable=False),
    sa.Column('diagnosis_id', sa.String(length=36), nullable=False),
    sa.Column('treatment', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['injury_classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('medical_records')
    op.drop_table('injury_classes')
    # ### end Alembic commands ###
