"""add token field in users

Revision ID: 662c5656f008
Revises: 3218ec759fe6
Create Date: 2024-12-04 12:35:32.211069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '662c5656f008'
down_revision = '3218ec759fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('token')

    # ### end Alembic commands ###
